version: "3.8"

services:
  web:
    image: rv369/project_20250419-web:1.0.0
    command: python bot.py
    volumes:
      - documents:/app/documents
      - db:/app/db
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

volumes:
  documents:
  db:
  