version: "3.8"

services:
  web:
    build: .
    command: python bot.py
    volumes:
      - documents:/app/documents
      - db:/app/db
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

volumes:
  documents:
  db:
  